"""Dataset generator for the SE(3) windy quadrotor.

Mirrors envs/pendulum_so3/datagen/windy_pendulum_3d_datagen.py, lifted from SO(3) to SE(3).

Per-sample layout (22 = 18 obs + 4 action):

    [ x_w(3) | vec(R)(9) | v_b(3) | omega_b(3) | u(4) ]
      world     row-major   body     body        rpm^2

The control convention matches the env: u_i = rpm_i^2 >= 0, so random
excitation is drawn AROUND the hover input u* = m g / (4 kf) and clipped at
zero, rather than around 0 as for the pendulum's torques.  This is option (a)
of notes/quadrotor-se3-ph-system.md s18.1 (short horizons, persistently
exciting open-loop input).

Deterministic (pH-ODE) data is the default: wind_force_std = wind_torque_std =
external_force_std = 0.
"""
from __future__ import annotations

import os
import pickle
import sys

import numpy as np

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(THIS_DIR, "..", "..", ".."))
QUAD_DIR = os.path.join(PROJECT_ROOT, "envs", "quadrotor_se3")
for _p in (PROJECT_ROOT, QUAD_DIR):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from quadrotor import quadrotor_se3, _exp_so3, _project_to_so3   # noqa: E402

OBS_DIM, ACT_DIM = 18, 4
STATE_DIM = OBS_DIM + ACT_DIM          # 22
IDX_X, IDX_R, IDX_V, IDX_W, IDX_U = (
    slice(0, 3), slice(3, 12), slice(12, 15), slice(15, 18), slice(18, 22))


def to_pickle(obj, path):
    with open(path, "wb") as fh:
        pickle.dump(obj, fh)


def from_pickle(path):
    with open(path, "rb") as fh:
        return pickle.load(fh)


def arrange_data(x, t, num_points=2):
    """Chop trajectories into overlapping windows of `num_points` samples.

    Identical to the pendulum version.
        x : (num_us, T, N, D)  ->  (num_us, num_points, N_windows, D)
    """
    assert 2 <= num_points <= len(t)
    x_stack = []
    for i in range(num_points):
        if i < num_points - 1:
            x_stack.append(x[:, i:-num_points + i + 1, :, :])
        else:
            x_stack.append(x[:, i:, :, :])
    x_stack = np.stack(x_stack, axis=1)
    x_stack = np.reshape(x_stack, (x.shape[0], num_points, -1, x.shape[3]))
    return x_stack, t[0:num_points]


# ── observation noise, on the manifold ────────────────────────────────────

def add_proper_noise_se3(clean, obs_noise_std, rng):
    """Geometric noise: R <- R exp([eps]_x); additive on x_w, v_b, omega.

    The control channel is left untouched (u is commanded, not measured).
    Mirrors add_proper_noise_3d in the pendulum datagen.
    """
    if obs_noise_std <= 0.0:
        return clean.copy()
    out = clean.copy()
    shape = out.shape[:-1]
    flat = out.reshape(-1, STATE_DIM)

    flat[:, IDX_X] += rng.normal(0.0, obs_noise_std, size=(flat.shape[0], 3))
    flat[:, IDX_V] += rng.normal(0.0, obs_noise_std, size=(flat.shape[0], 3))
    flat[:, IDX_W] += rng.normal(0.0, obs_noise_std, size=(flat.shape[0], 3))

    eps = rng.normal(0.0, obs_noise_std, size=(flat.shape[0], 3))
    for i in range(flat.shape[0]):
        R = flat[i, IDX_R].reshape(3, 3)
        flat[i, IDX_R] = (R @ _exp_so3(eps[i])).reshape(9)
    return flat.reshape(*shape, STATE_DIM)


# ── trajectory sampling ───────────────────────────────────────────────────

# ── geometric PID / PD controller, used for u_mode="pid" ──────────────────
# The LieGroupHamDL quadrotor data is generated by a DSL PID controller flying
# to setpoints, not by open-loop excitation.  This is the same idea with the
# Lie-style geometric controller already used by the env demo: a position PD
# sets the desired force, its direction becomes the desired body-z axis, and an
# attitude PD tracks that.  The resulting wrench is mapped back to rotor speeds
# through the (invertible) thrust/torque rows of G.

PID_GAINS = dict(kp_pos=2.0, kd_pos=2.5, kr=10.0, komega=3.0)


def _vee(W):
    return np.array([W[2, 1], W[0, 2], W[1, 0]], dtype=np.float64)


def pid_control(env, target_pos, target_yaw, gains=PID_GAINS):
    """Rotor speeds u = A^-1 [T; tau] that drive the drone toward a setpoint."""
    x, R, v_b, om = env.get_state()
    v_w = R @ v_b
    e3 = np.array([0.0, 0.0, 1.0])

    F_des = env.m * (gains["kp_pos"] * (target_pos - x)
                     - gains["kd_pos"] * v_w + env.g * e3)
    b3 = F_des / max(np.linalg.norm(F_des), 1e-9)
    c1 = np.array([np.cos(target_yaw), np.sin(target_yaw), 0.0])
    b2 = np.cross(b3, c1)
    if np.linalg.norm(b2) < 1e-6:            # b3 nearly parallel to c1
        b2 = np.cross(b3, np.array([0.0, 1.0, 0.0]))
    b2 /= max(np.linalg.norm(b2), 1e-9)
    R_des = np.stack([np.cross(b2, b3), b2, b3], axis=1)

    T = float(F_des @ (R @ e3))
    e_R = 0.5 * _vee(R_des.T @ R - R.T @ R_des)
    tau = -gains["kr"] * e_R - gains["komega"] * om
    u = np.linalg.solve(env.G[2:6, :], np.hstack([T, tau]))
    return np.clip(u, 0.0, env.max_u)


def sample_windy_quadrotor_se3(
    seed=0,
    timesteps=20,
    trials=64,
    u=None,
    friction_coeff=0.5,
    angular_friction_coeff=None,
    external_force_type="sine",
    external_force_std=0.0,
    external_force_direction=(1.0, 0.0, 0.0),
    wind_force_std=0.0,
    wind_torque_std=0.0,
    g=9.81,
    m=1.0,
    J_diag=(0.5, 0.5, 1.0),
    arm=1.0,
    kf_coeff=1.0,
    km_coeff=0.1,
    dt=0.05,
    random_u=True,
    random_u_scale=1.0,
    u_hold=1,
    u_mode="random",
    pid_target_box=1.0,
    max_speed=25.0,
    max_omega=25.0,
    **kwargs,
):
    """Roll `trials` trajectories of `timesteps` samples each.

    Returns (trajs, tspan) with trajs of shape (timesteps, trials, 22).

    random_u: u ~ U(u* - scale, u* + scale) per step, clipped to >= 0, where
        u* = m g / (4 kf) is the hover input.  Drawing around hover (not
        around 0) keeps the excitation in the physically meaningful regime.
    max_speed / max_omega: reject-and-resample filter.  A quadrotor is
        open-loop unstable, so an unlucky initial attitude plus random thrust
        can diverge; this keeps the dataset in a well-conditioned region.
    """
    angular_friction_coeff = (friction_coeff if angular_friction_coeff is None
                              else angular_friction_coeff)
    env = quadrotor_se3(
        g=g, m=m, J_diag=J_diag, arm=arm, dt=dt,
        kf_coeff=kf_coeff, km_coeff=km_coeff,
        linear_damping_coeff=friction_coeff,
        angular_damping_coeff=angular_friction_coeff,
        external_force_type=external_force_type,
        external_force_std=external_force_std,
        external_force_direction=external_force_direction,
        wind_force_std=wind_force_std,
        wind_torque_std=wind_torque_std,
        render_mode=None, seed=seed, **kwargs)

    u_hover = m * g / (4.0 * max(kf_coeff, 1e-12))
    u_fixed = (np.full(ACT_DIM, u_hover) if u is None
               else np.asarray(u, dtype=np.float64).reshape(ACT_DIM))

    trajs = []
    main_seed = int(seed)
    n_reject = 0
    for _ in range(int(trials)):
        while True:
            obs, _ = env.reset(seed=main_seed)
            act_rng = np.random.default_rng(main_seed + 12345)

            # one random setpoint per trajectory, mirroring their 18 goals
            tgt_pos = act_rng.uniform(-pid_target_box, pid_target_box, size=3)
            tgt_yaw = float(act_rng.uniform(-np.pi, np.pi))

            def draw():
                if u_mode == "pid":
                    return pid_control(env, tgt_pos, tgt_yaw)
                if not random_u:
                    return u_fixed.copy()
                return np.clip(u_fixed + act_rng.uniform(
                    -random_u_scale, random_u_scale, size=ACT_DIM), 0.0, None)

            # u_hold > 1 keeps u constant for that many consecutive env steps,
            # i.e. a control rate slower than the simulation rate (the
            # LieGroupHamDL quadrotor data uses 48 Hz control inside 240 Hz
            # physics, so u is exactly constant across each training window).
            # DATAGEN CONVENTION (identical to the 3D pendulum datagen):
            # row k+1 carries the control that drove step k -> k+1, and row 0
            # repeats u_0.  Consumers must therefore read the control for step
            # k from x[k+1], exactly as windy_pendulum_3d's segment_rollout
            # and ph_gp_ode's _rollout_single already do.
            curr_u = draw()
            traj = [np.concatenate((obs, curr_u.astype(np.float32)))]
            for _t in range(int(timesteps) - 1):
                obs, _r, _term, _trunc, _info = env.step(curr_u)
                traj.append(np.concatenate((obs, curr_u.astype(np.float32))))
                if (_t + 1) % max(1, int(u_hold)) == 0:
                    curr_u = draw()
            traj = np.stack(traj, axis=0)

            v_ok = np.abs(traj[:, IDX_V]).max() < max_speed
            w_ok = np.abs(traj[:, IDX_W]).max() < max_omega
            if np.isfinite(traj).all() and v_ok and w_ok:
                break
            n_reject += 1
            main_seed += 10
        trajs.append(traj)
        main_seed += 1
    env.close()

    if n_reject:
        print(f"  ({n_reject} trajectories rejected by the speed filter and resampled)")
    trajs = np.transpose(np.stack(trajs, axis=0), (1, 0, 2))   # (T, N, 22)
    return trajs, np.arange(int(timesteps)) * dt


# ── dataset assembly ──────────────────────────────────────────────────────

def get_dataset(
    seed=0,
    samples=64,
    test_split=0.5,
    save_dir=None,
    us=None,
    timesteps=20,
    obs_noise_std=0.0,
    friction_coeff=0.5,
    angular_friction_coeff=None,
    external_force_type="sine",
    external_force_std=0.0,
    external_force_direction=(1.0, 0.0, 0.0),
    wind_force_std=0.0,
    wind_torque_std=0.0,
    g=9.81, m=1.0, J_diag=(0.5, 0.5, 1.0), arm=1.0,
    kf_coeff=1.0, km_coeff=0.1, dt=0.05,
    random_u=True, random_u_scale=1.0, u_hold=1,
    u_mode="random", pid_target_box=1.0,
    regenerate=False,
    **kwargs,
):
    """Build (or load) the SE(3) quadrotor dataset.

        data['x']      : (num_us, T, N_train, 22)  train  (noisy if requested)
        data['test_x'] : (num_us, T, N_test,  22)  test   (clean targets)
        data['t']      : (T,)
    """
    if save_dir is None:
        raise ValueError("save_dir must be specified.")
    os.makedirs(save_dir, exist_ok=True)

    tag = (f"se3quad_s{seed}_n{samples}_T{timesteps}_dt{dt:g}_hold{u_hold}"
           f"_fric{friction_coeff:g}"
           f"_obs{obs_noise_std:g}_wf{wind_force_std:g}_wt{wind_torque_std:g}"
           f"_ext{external_force_std:g}"
           f"{'_randu' + f'{random_u_scale:g}' if random_u else ''}"
           f"{'_' + u_mode if u_mode != 'random' else ''}.pkl")
    out_path = os.path.join(save_dir, tag)
    if os.path.isfile(out_path) and not regenerate:
        print(f"Loading cached dataset: {out_path}")
        return from_pickle(out_path), out_path

    us_list = [None] if us is None else list(us)
    print(f"Generating SE(3) quadrotor dataset -> {out_path}")
    print(f"  {len(us_list)} input set(s) x {samples} trajectories x {timesteps} steps")

    trajs_force, tspan = [], None
    for u in us_list:
        trajs, tspan = sample_windy_quadrotor_se3(
            seed=seed, timesteps=timesteps, trials=samples, u=u,
            friction_coeff=friction_coeff,
            angular_friction_coeff=angular_friction_coeff,
            external_force_type=external_force_type,
            external_force_std=external_force_std,
            external_force_direction=external_force_direction,
            wind_force_std=wind_force_std, wind_torque_std=wind_torque_std,
            g=g, m=m, J_diag=J_diag, arm=arm,
            kf_coeff=kf_coeff, km_coeff=km_coeff, dt=dt,
            random_u=random_u, random_u_scale=random_u_scale,
            u_hold=u_hold, u_mode=u_mode, pid_target_box=pid_target_box,
            **kwargs)
        trajs_force.append(trajs)

    all_clean = np.stack(trajs_force, axis=0)          # (num_us, T, N, 22)
    split_ix = (int(samples * 0.5) if test_split >= 0.5
                else int(samples * (1.0 - test_split)))
    train_clean = all_clean[:, :, :split_ix, :]
    test_clean = all_clean[:, :, split_ix:, :]

    data = {"t": tspan, "settings": dict(
        seed=seed, samples=samples, test_split=test_split, timesteps=timesteps,
        obs_noise_std=obs_noise_std, friction_coeff=friction_coeff,
        angular_friction_coeff=(friction_coeff if angular_friction_coeff is None
                                else angular_friction_coeff),
        external_force_type=external_force_type,
        external_force_std=external_force_std,
        wind_force_std=wind_force_std, wind_torque_std=wind_torque_std,
        g=g, m=m, J_diag=tuple(J_diag), arm=arm,
        kf_coeff=kf_coeff, km_coeff=km_coeff, dt=dt,
        random_u=random_u, random_u_scale=random_u_scale, u_hold=u_hold,
        u_mode=u_mode, u_hover=m * g / (4.0 * kf_coeff))}

    if obs_noise_std > 0.0:
        print(f"Applying SE(3) observation noise (std={obs_noise_std})...")
        data["x"] = add_proper_noise_se3(train_clean, obs_noise_std,
                                         np.random.default_rng(seed + 999))
        data["test_x"] = test_clean
        data["test_x_noisy"] = add_proper_noise_se3(
            test_clean, obs_noise_std, np.random.default_rng(seed + 1999))
    else:
        print("No observation noise added.")
        data["x"] = train_clean
        data["test_x"] = test_clean
        data["test_x_noisy"] = test_clean

    to_pickle(data, out_path)
    return data, out_path


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser(description="Generate the SE(3) quadrotor dataset.")
    p.add_argument("--save_dir", default=os.path.join(PROJECT_ROOT, "datasets", "windy_quadrotor_se3"))
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--samples", type=int, default=64)
    p.add_argument("--timesteps", type=int, default=20)
    p.add_argument("--friction_coeff", type=float, default=0.5)
    p.add_argument("--obs_noise_std", type=float, default=0.0)
    p.add_argument("--random_u_scale", type=float, default=1.0)
    p.add_argument("--no_random_u", action="store_true")
    p.add_argument("--regenerate", action="store_true")
    a = p.parse_args()
    d, path = get_dataset(
        seed=a.seed, samples=a.samples, timesteps=a.timesteps,
        save_dir=a.save_dir, friction_coeff=a.friction_coeff,
        obs_noise_std=a.obs_noise_std, random_u=not a.no_random_u,
        random_u_scale=a.random_u_scale, regenerate=a.regenerate)
    x = d["x"]
    print(f"\ntrain {x.shape}   test {d['test_x'].shape}   t {d['t'].shape}")
    f = x.reshape(-1, STATE_DIM)
    for nm, sl in (("x_w", IDX_X), ("v_b", IDX_V), ("omega", IDX_W), ("u", IDX_U)):
        print(f"  {nm:<6} range [{f[:, sl].min():+8.3f}, {f[:, sl].max():+8.3f}]")
    R = f[:, IDX_R].reshape(-1, 3, 3)
    orth = np.abs(np.einsum('nij,nkj->nik', R, R) - np.eye(3)).max()
    print(f"  max |R R^T - I| over the dataset = {orth:.3e}")
