"""Config-file + command-line plumbing for the SE(3) quadrotor environment.

Resolution order (later wins):

    quadrotor_se3.__init__ defaults   <   YAML config file   <   CLI flags / kwargs

The CLI flags are generated by *reflecting over* ``quadrotor_se3.__init__``, so
adding an argument to the env automatically makes it configurable and
overridable — there is no hand-maintained list of parameter names in this file.

Command-line use (any config value can be overridden)::

    python envs/quadrotor_se3_port_ham/quadrotor.py \
        --config configs/quadrotor_se3/envs/sde.yaml \
        --external_force_type random --wind_force_std 0.8

Programmatic use::

    env = quadrotor_se3.from_config("configs/quadrotor_se3/envs/ode.yaml")
    env = quadrotor_se3.from_config("configs/.../sde.yaml", seed=7)   # kwargs win

Inspect what a config + flags actually resolve to, without building anything::

    python envs/quadrotor_se3_port_ham/env_config.py \
        --config configs/quadrotor_se3/envs/sde.yaml --wind_force_std 0.8
"""
from __future__ import annotations

import argparse
import os
import sys
import typing

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if _THIS_DIR not in sys.path:
    sys.path.insert(0, _THIS_DIR)

from quadrotor import quadrotor_se3  # noqa: E402

PROJECT_ROOT = os.path.abspath(os.path.join(_THIS_DIR, "..", ".."))
CONFIG_DIR = os.path.join(PROJECT_ROOT, "configs", "quadrotor_se3", "envs")
ODE_CONFIG = os.path.join(CONFIG_DIR, "ode.yaml")
SDE_CONFIG = os.path.join(CONFIG_DIR, "sde.yaml")

# Enumerated arguments the env itself validates.  Listing them here only moves
# the error earlier (argparse instead of a ValueError at construction time).
CHOICES = {
    "external_force_type": ["sine", "square", "random", "constant"],
    "render_backend": ["pybullet", "matplotlib"],
    "render_mode": ["human", "rgb_array"],
    "ori_rep": ["rotmat"],
}

# Short help strings; anything missing still gets a working flag.
HELP = {
    "g": "gravitational acceleration [m/s^2]",
    "m": "mass [kg]",
    "J_diag": "body inertia diagonal (3 floats)",
    "arm": "rotor arm length [m]; lever a = arm/sqrt(2)",
    "dt": "env step [s]; 10 fixed substeps of h = dt/10",
    "kf_coeff": "thrust gain k_f (mean)",
    "kf_std": "std of k_f; 0 = fixed",
    "km_coeff": "yaw reaction-drag gain k_m (mean)",
    "km_std": "std of k_m; 0 = fixed",
    "linear_damping_coeff": "translational friction d_lin (mean)",
    "linear_damping_std": "std of d_lin; 0 = fixed",
    "angular_damping_coeff": "rotational friction d_ang (mean)",
    "angular_damping_std": "std of d_ang; 0 = fixed",
    "resample_coeffs_every_step": "redraw coefficients each step (else once per episode)",
    "external_force_type": "deterministic wind waveform",
    "external_force_std": "deterministic wind amplitude sigma_w",
    "external_force_direction": "world wind direction (3 floats, normalised)",
    "wind_force_std": "STOCHASTIC force channel sigma_f (0 => ODE)",
    "wind_torque_std": "STOCHASTIC torque channel sigma_tau (0 => ODE)",
    "obs_noise_std": "geometric observation noise sigma_o",
    "max_u": "action_space bound only - the env never clips u",
    "ori_rep": "orientation representation",
    "render_mode": "None | human | rgb_array",
    "render_backend": "pybullet (CF2X model) | matplotlib (schematic)",
    "seed": "dynamics RNG seed; obs-noise RNG uses seed+1",
}


def param_spec() -> dict:
    """{name: (annotation, default)} reflected off quadrotor_se3.__init__."""
    import inspect

    hints = typing.get_type_hints(quadrotor_se3.__init__)
    sig = inspect.signature(quadrotor_se3.__init__)
    spec = {}
    for name, p in sig.parameters.items():
        if name in ("self", "args", "kwargs"):
            continue
        spec[name] = (hints.get(name, str), p.default)
    return spec


def _unwrap_optional(ann):
    """Optional[X] / X | None  ->  X."""
    origin = typing.get_origin(ann)
    is_union = origin is typing.Union
    try:                                     # PEP 604 unions (X | None)
        import types
        is_union = is_union or origin is types.UnionType
    except AttributeError:                   # pragma: no cover
        pass
    if is_union:
        non_none = [a for a in typing.get_args(ann) if a is not type(None)]
        if len(non_none) == 1:
            return non_none[0]
    return ann


def _add_arg(group, name, ann, default):
    """Add one auto-generated override flag.  Default is always None so we can
    tell 'user did not pass it' from 'user passed the env default'."""
    help_txt = HELP.get(name, f"override {name}")
    help_txt = f"{help_txt}  [env default: {default!r}]"
    inner = _unwrap_optional(ann)

    if inner is bool:
        group.add_argument(f"--{name}", default=None,
                           action=argparse.BooleanOptionalAction, help=help_txt)
        return
    if typing.get_origin(inner) is tuple:
        n = len(typing.get_args(inner))
        group.add_argument(f"--{name}", type=float, nargs=n, default=None,
                           metavar=tuple(f"F{i}" for i in range(n)), help=help_txt)
        return
    kw = {"type": inner if inner in (int, float, str) else str,
          "default": None, "help": help_txt}
    if name in CHOICES:
        kw["choices"] = CHOICES[name]
    group.add_argument(f"--{name}", **kw)


def load_config(path: str):
    """Read a YAML env config.  Returns (kwargs, metadata).

    Keys starting with '_' are metadata.  Any other key that is not a
    constructor argument raises, so typos surface immediately.
    """
    try:
        import yaml
    except ImportError as exc:                                  # pragma: no cover
        raise ImportError("PyYAML is required to read env configs "
                          "(pip install pyyaml)") from exc

    path = os.path.abspath(path)
    if not os.path.isfile(path):
        raise FileNotFoundError(f"env config not found: {path}")
    with open(path, "r", encoding="utf-8") as fh:
        raw = yaml.safe_load(fh) or {}
    if not isinstance(raw, dict):
        raise ValueError(f"env config must be a YAML mapping, got {type(raw).__name__}: {path}")

    spec = param_spec()
    kwargs, meta = {}, {}
    for key, val in raw.items():
        if str(key).startswith("_"):
            meta[key] = val
            continue
        if key not in spec:
            raise KeyError(
                f"unknown env argument {key!r} in {path}.\n"
                f"  valid arguments: {', '.join(sorted(spec))}")
        kwargs[key] = val
    return kwargs, meta


def build_parser(description=None, default_config=None, parser=None):
    """Argparse parser with --config plus one override flag per env argument."""
    if parser is None:
        parser = argparse.ArgumentParser(description=description)
    parser.add_argument("--config", type=str, default=default_config,
                        help=f"path to a YAML env config (see {CONFIG_DIR})")
    grp = parser.add_argument_group(
        "env overrides", "each flag overrides the corresponding config value")
    for name, (ann, default) in param_spec().items():
        _add_arg(grp, name, ann, default)
    return parser


def kwargs_from_args(args, **fallbacks) -> dict:
    """Resolve config file + CLI flags into quadrotor_se3(**kwargs).

    `fallbacks` are applied only where neither the config nor the CLI spoke.
    """
    spec = param_spec()
    kwargs = {}
    if getattr(args, "config", None):
        kwargs.update(load_config(args.config)[0])
    for name in spec:
        val = getattr(args, name, None)
        if val is not None:                 # None == flag not supplied
            kwargs[name] = val
    for name, val in fallbacks.items():
        kwargs.setdefault(name, val)
    return kwargs


def env_kwargs_from_config(config_path: str, **overrides) -> dict:
    """Config file merged with explicit keyword overrides (overrides win)."""
    spec = param_spec()
    bad = [k for k in overrides if k not in spec]
    if bad:
        raise KeyError(f"not env arguments: {bad}\n  valid: {', '.join(sorted(spec))}")
    kwargs, _ = load_config(config_path)
    kwargs.update(overrides)
    return kwargs


def describe(kwargs: dict, config_path=None, meta=None) -> str:
    """Human-readable dump of a resolved configuration."""
    lines = []
    if config_path:
        lines.append(f"config : {config_path}")
    for key, val in (meta or {}).items():
        lines.append(f"{key:7s}: {val}")
    lines.append("-" * 62)
    for name in param_spec():
        if name in kwargs:
            lines.append(f"  {name:<28} = {kwargs[name]!r}")
    return "\n".join(lines)


def is_stochastic(kwargs: dict) -> bool:
    """True when any Brownian channel is active (i.e. an SDE, not an ODE)."""
    spec = param_spec()
    def _get(n):
        return float(kwargs.get(n, spec[n][1]))
    return _get("wind_force_std") > 0.0 or _get("wind_torque_std") > 0.0


if __name__ == "__main__":
    p = build_parser(description="Resolve an SE(3) quadrotor env config "
                                 "(config file + CLI overrides) and print it.")
    a = p.parse_args()
    if not a.config:
        p.error("--config is required (try configs/quadrotor_se3/envs/sde.yaml)")
    kw = kwargs_from_args(a)
    print(describe(kw, a.config, load_config(a.config)[1]))
    print("-" * 62)
    print(f"  -> {'SDE (stochastic)' if is_stochastic(kw) else 'ODE (deterministic)'}")
